# Single argument analysis only configuration
#
# Use this configuration to focus exclusively on single argument reconstruction tasks.

SingleArgumentAnalysis:
  weight: 1.0
  datasets:
    - path: "DebateLabKIT/arguments-and-debates"
      subset: "arguments-pros-and-cons-2010"
      split: "train"

MultiArgumentAnalysis:
  weight: 0.0
  datasets:
